const watches = [
  {
    id: 1,
    name: "Casio G-Shock GA-2100",
    brand: "Casio",
    type: "Quartz",
    material: "Resin",
    size: 45,
    price: 3500000,
    review: 4.5,
    sold: 1200,
    image: "1.webp",
  },
  {
    id: 2,
    name: "Rolex Submariner",
    brand: "Rolex",
    type: "Automatic",
    material: "Stainless Steel",
    size: 41,
    price: 300000000,
    review: 5.0,
    sold: 800,
    image: "2.webp",
  },
  {
    id: 3,
    name: "Seiko Presage Cocktail Time",
    brand: "Seiko",
    type: "Automatic",
    material: "Stainless Steel",
    size: 40,
    price: 10000000,
    review: 4.7,
    sold: 1500,
    image: "3.webp",
  },
  {
    id: 4,
    name: "Apple Watch Series 9",
    brand: "Apple",
    type: "Smartwatch",
    material: "Aluminum",
    size: 45,
    price: 12000000,
    review: 4.6,
    sold: 5000,
    image: "4.jpg",
  },
  {
    id: 5,
    name: "Tissot PRX Powermatic 80",
    brand: "Tissot",
    type: "Automatic",
    material: "Stainless Steel",
    size: 40,
    price: 15000000,
    review: 3.8,
    sold: 900,
    image: "5.jpg",
  },
  {
    id: 6,
    name: "Omega Speedmaster",
    brand: "Omega",
    type: "Automatic",
    material: "Stainless Steel",
    size: 42,
    price: 200000000,
    review: 2.0,
    sold: 600,
    image: "6.webp",
  },
  {
    id: 7,
    name: "Tag Heuer Carrera",
    brand: "Tag Heuer",
    type: "Automatic",
    material: "Titanium",
    size: 44,
    price: 180000000,
    review: 4.9,
    sold: 700,
    image: "7.webp",
  },
  {
    id: 8,
    name: "Fossil Gen 6",
    brand: "Fossil",
    type: "Smartwatch",
    material: "Stainless Steel",
    size: 44,
    price: 7000000,
    review: 1.3,
    sold: 2500,
    image: "8.png",
  },
  {
    id: 9,
    name: "Samsung Galaxy Watch 6",
    brand: "Samsung",
    type: "Smartwatch",
    material: "Aluminum",
    size: 44,
    price: 8000000,
    review: 4.5,
    sold: 3200,
    image: "9.png",
  },
  {
    id: 10,
    name: "Garmin Fenix 7",
    brand: "Garmin",
    type: "Smartwatch",
    material: "Titanium",
    size: 47,
    price: 15000000,
    review: 4.7,
    sold: 1800,
    image: "10.png",
  },
  {
    id: 11,
    name: "Casio Edifice EFV-100D",
    brand: "Casio",
    type: "Quartz",
    material: "Stainless Steel",
    size: 42,
    price: 4500000,
    review: 4.2,
    sold: 950,
    image: "11.jfif",
  },
  {
    id: 12,
    name: "Rolex Daytona",
    brand: "Rolex",
    type: "Automatic",
    material: "Stainless Steel",
    size: 40,
    price: 350000000,
    review: 4.8,
    sold: 650,
    image: "12.png",
  },
  {
    id: 13,
    name: "Seiko 5 Sports",
    brand: "Seiko",
    type: "Automatic",
    material: "Stainless Steel",
    size: 39,
    price: 8500000,
    review: 4.4,
    sold: 1300,
    image: "13.png",
  },
  {
    id: 14,
    name: "Apple Watch SE",
    brand: "Apple",
    type: "Smartwatch",
    material: "Aluminum",
    size: 40,
    price: 9000000,
    review: 4.5,
    sold: 4200,
    image: "14.jpg",
  },
  {
    id: 15,
    name: "Tissot Le Locle Powermatic",
    brand: "Tissot",
    type: "Automatic",
    material: "Stainless Steel",
    size: 41,
    price: 16000000,
    review: 4.0,
    sold: 800,
    image: "15.jpg",
  },
  {
    id: 16,
    name: "Omega Seamaster Diver 300M",
    brand: "Omega",
    type: "Automatic",
    material: "Stainless Steel",
    size: 43,
    price: 250000000,
    review: 4.7,
    sold: 550,
    image: "16.webp",
  },
  {
    id: 17,
    name: "Tag Heuer Monaco Calibre 11",
    brand: "Tag Heuer",
    type: "Automatic",
    material: "Titanium",
    size: 42,
    price: 190000000,
    review: 4.8,
    sold: 500,
    image: "17.webp",
  },
  {
    id: 18,
    name: "Fossil Hybrid HR",
    brand: "Fossil",
    type: "Hybrid",
    material: "Leather",
    size: 43,
    price: 6000000,
    review: 3.9,
    sold: 2100,
    image: "18.webp",
  },
  {
    id: 19,
    name: "Samsung Galaxy Watch 5 Pro",
    brand: "Samsung",
    type: "Smartwatch",
    material: "Aluminum",
    size: 45,
    price: 10000000,
    review: 4.6,
    sold: 3000,
    image: "19.jfif",
  },
  {
    id: 20,
    name: "Garmin Forerunner 955",
    brand: "Garmin",
    type: "Smartwatch",
    material: "Polymer",
    size: 44,
    price: 17000000,
    review: 4.5,
    sold: 1600,
    image: "20.jpg",
  },
  {
    id: 21,
    name: "Casio Pro Trek PRW-6000",
    brand: "Casio",
    type: "Quartz",
    material: "Resin",
    size: 47,
    price: 5000000,
    review: 4.3,
    sold: 800,
    image: "21.webp",
  },
  {
    id: 22,
    name: "Rolex Datejust 36",
    brand: "Rolex",
    type: "Automatic",
    material: "Stainless Steel & Gold",
    size: 36,
    price: 280000000,
    review: 4.9,
    sold: 720,
    image: "22.png",
  },
  {
    id: 23,
    name: "Seiko Prospex Turtle",
    brand: "Seiko",
    type: "Automatic",
    material: "Stainless Steel",
    size: 41,
    price: 12000000,
    review: 4.6,
    sold: 1100,
    image: "23.avif",
  },
  {
    id: 24,
    name: "Apple Watch Ultra",
    brand: "Apple",
    type: "Smartwatch",
    material: "Titanium",
    size: 49,
    price: 15000000,
    review: 4.7,
    sold: 3800,
    image: "24.jpg",
  },
  {
    id: 25,
    name: "Tissot T-Touch Connect Solar",
    brand: "Tissot",
    type: "Smartwatch",
    material: "Stainless Steel",
    size: 42,
    price: 13000000,
    review: 4.1,
    sold: 950,
    image: "25.jpg",
  },
  {
    id: 26,
    name: "Omega Constellation Co-Axial",
    brand: "Omega",
    type: "Automatic",
    material: "Stainless Steel",
    size: 39,
    price: 220000000,
    review: 4.4,
    sold: 470,
    image: "26.webp",
  },
  {
    id: 27,
    name: "Tag Heuer Formula 1",
    brand: "Tag Heuer",
    type: "Automatic",
    material: "Stainless Steel",
    size: 43,
    price: 170000000,
    review: 4.2,
    sold: 680,
    image: "27.avif",
  },
  {
    id: 28,
    name: "Fossil Q Explorist",
    brand: "Fossil",
    type: "Smartwatch",
    material: "Aluminum",
    size: 42,
    price: 7500000,
    review: 3.7,
    sold: 2300,
    image: "28.webp",
  },
  {
    id: 29,
    name: "Samsung Galaxy Watch Active 2",
    brand: "Samsung",
    type: "Smartwatch",
    material: "Aluminum",
    size: 42,
    price: 8500000,
    review: 4.3,
    sold: 2900,
    image: "29.webp",
  },
  {
    id: 30,
    name: "Garmin Vivoactive 4",
    brand: "Garmin",
    type: "Smartwatch",
    material: "Polymer",
    size: 45,
    price: 14000000,
    review: 4.6,
    sold: 2000,
    image: "30.jpg",
  },
];

export default watches;