const watches = [
    {
      id: 1,
      name: "Casio G-Shock GA-2100",
      brand: "Casio",
      type: "Quartz",
      material: "Resin",
      size: 45,
      price: 3500000,
      image: "1.webp",
    },
    {
      id: 2,
      name: "Rolex Submariner",
      brand: "Rolex",
      type: "Automatic",
      material: "Stainless Steel",
      size: 41,
      price: 300000000,
      image: "2.webp",
    },
    {
      id: 3,
      name: "Seiko Presage Cocktail Time",
      brand: "Seiko",
      type: "Automatic",
      material: "Stainless Steel",
      size: 40,
      price: 10000000,
      image: "3.webp",
    },
    {
      id: 4,
      name: "Apple Watch Series 9",
      brand: "Apple",
      type: "Smartwatch",
      material: "Aluminum",
      size: 45,
      price: 12000000,
      image: "4.jpg",
    },
    {
      id: 5,
      name: "Tissot PRX Powermatic 80",
      brand: "Tissot",
      type: "Automatic",
      material: "Stainless Steel",
      size: 40,
      price: 15000000,
      image: "5.jpg",
    },
    {
      id: 6,
      name: "Omega Speedmaster",
      brand: "Omega",
      type: "Automatic",
      material: "Stainless Steel",
      size: 42,
      price: 200000000,
      image: "6.webp",
    },
    {
      id: 7,
      name: "Tag Heuer Carrera",
      brand: "Tag Heuer",
      type: "Automatic",
      material: "Titanium",
      size: 44,
      price: 180000000,
      image: "7.webp",
    },
    {
      id: 8,
      name: "Fossil Gen 6",
      brand: "Fossil",
      type: "Smartwatch",
      material: "Stainless Steel",
      size: 44,
      price: 7000000,
      image: "8.png",
    },
    {
      id: 9,
      name: "Samsung Galaxy Watch 6",
      brand: "Samsung",
      type: "Smartwatch",
      material: "Aluminum",
      size: 44,
      price: 8000000,
      image: "9.png",
    },
    {
      id: 10,
      name: "Garmin Fenix 7",
      brand: "Garmin",
      type: "Smartwatch",
      material: "Titanium",
      size: 47,
      price: 15000000,
      image: "10.png",
    },
  ];
  
export default watches;